### ISSUE TITLE
Button in docu pages does not work

### ISSUE THREAD

**Issue by smaiLee** [SmartVisuTNG/smartvisu#12]
In the docu pages of basic.dual the micro "dw" button (on the lower left of page) does not work.
This bug already exists in version 2.7 (and likely earlier).

![image](https://cloud.githubusercontent.com/assets/20517059/17833562/2d054748-6721-11e6-8303-0889bbb71566.png)

**Comment by i-am-offline** [comment]
Should be fixed with this. Pls retest and close.

**Comment by smaiLee** [comment]
Thx, it works
