### ISSUE TITLE
Some icons in docu pages are not shown

### ISSUE THREAD

**Issue by smaiLee** [SmartVisuTNG/smartvisu#14]
Affected pages:
- basic.glue
- basic.shifter
- Design - Quad
- Design - Popups
- Misc - Overview

**Comment by i-am-offline** [comment]
I'll have a look at this ...

**Comment by i-am-offline** [comment]
The mentioned pages should be finished. As expected most times still png images were used.
I'll check in the next days if there are any other png images left over in the docu pages.
I also came across some other issues, but I will create new issues for them.

**Comment by smaiLee** [comment]
Perhaps we should replace the PNGs automatically in user pages (serverside or clientside by JS).
Otherwise every user has to edit his pages or with autogeneration even SH items.

**Comment by i-am-offline** [comment]
Mhm ... I don't like stuff that changes configurations etc. automatically.
It can fail and everyone is wondering why because nobody remembers the automatic changes ...
However I could imagine some kind of "page checker" available from the config page. It can be developed in several steps
1. Read config files, search for missing png files
2. Propose changes for found parts
3. Actually do the changes if the user wants

**Comment by smaiLee** [comment]
I do not want to change configuration or pages but I would replace references to earlier PNG on the fly.
In [base.js](https://github.com/SmartVisuTNG/smartvisu/blob/master/lib/base/base.js#L219) SVG are made inline. We could extend this and load the apropriate SVG inline if theres a reference to an old PNG.

**Comment by i-am-offline** [comment]
I think this would require quite some processing on the client side which could negatively affect the performance. Therefore I think it's better if the templates do not use nonexisting png files. If we can support the users to check and fix their templates they can just change their templates and will be done. No need to perform additional processing on every page request.

Regarding this issue I've finished checking images and docu. So I would propose to close this issue and continue the discussion regarding the images in #20
