### ISSUE TITLE
Adjust documentation to 2.9 (new Plots, more information, Releasenotes, etc.)

### ISSUE THREAD

**Issue by psilo909** [SmartVisuTNG/smartvisu#16]
The new Plots and other things (like the "0h" default instead of 0) need to be adjusted and added in the documentation.

We could also help new users by improving the documentation, as the documentation always was a problem with old SmartVisu.

Moreover, some documentation for developers would be very nice (drivers, new widgets, data handling, etc)

Also take care to log your changes in releasenotes (wiki?)

**Comment by smaiLee** [comment]
I have created changelog.md in the root, please enter up your changed stuff there.

**Comment by smaiLee** [comment]
This issue was moved to Martin-Gleiss/smartvisu#63
