### ISSUE TITLE
Charts buggy after "now", "0", "0h" fix

### ISSUE THREAD

**Issue by psilo909** [SmartVisuTNG/smartvisu#17]
my charts are buggy after merging the 0h fix.

the last values overlap and e.g. form a "z" style line. 

![vbvb](https://cloud.githubusercontent.com/assets/15831643/17835857/47aafe68-677f-11e6-8a26-37bf16a7d2b5.PNG)

**Comment by i-am-offline** [comment]
Just fetched SNHG (release 1.2) and Smartvisu (latest master branch).
Plot,period working as expected
![plot](https://cloud.githubusercontent.com/assets/9217443/17836021/203a7736-6785-11e6-96cb-31397930a2d2.png)

**Comment by psilo909** [comment]
interesting ;)

**Comment by psilo909** [comment]
how is your plot.period set up?

**Comment by psilo909** [comment]
same behavior for 0, now and 0h:

{{ plot.period('corridor_gf_humdity_plot', 'corridor_gf.temperature.humidity', 'avg', '12h', 'now', '', '', '', 'Luftfeuchte', '#00a', 'line', 'Luftfeuchte in %') }}

i can try to reset the database..

**Comment by i-am-offline** [comment]
{{ plot.period(
			'waermepumpe-popup-warmwasser-plot-1', 
			['zentral.heizung.warmwasser','zentral.heizung.zirkulationrl'],
			'avg',  
			'24h', 0, '','',144,
			['Austritt', 'RL Zirkulation'], 
			['#aa0', '#a00'], 
			['spline', 'spline'],
			['24 Stunden', '°C']) }}

**Comment by psilo909** [comment]
just deleted my database and will retry

**Comment by i-am-offline** [comment]
"0" and "now" will be translated into "0h". Could you try "1s" as tmax if it's still not working?

**Comment by psilo909** [comment]
still:
![fg](https://cloud.githubusercontent.com/assets/15831643/17836085/95e6d55a-6786-11e6-9133-f737e8f4f1c8.PNG)

**Comment by psilo909** [comment]
trying 1s

**Comment by psilo909** [comment]
{{ plot.period('outside_temperature_plot_24h', ['knx_global.weather.temperature','eta_unit.temperature_outside.value','dwd_weather.temperatur'], 'avg', '24h', '1s', '', '', '', ['Wetterstation','Garage','DWD'], ['#aa0', '#a00', '#00a'], 'line', 'Temperatur in °C') }}
 Chart not working anymore..

**Comment by i-am-offline** [comment]
OK. Just checked. The sqlite_visu2_8 plugin from SHNG does not know about "s" (seconds). Please try "1i" (one minute) instead.

O.T._ As "1s" is a valid value accoding to http://docu.smartvisu.de/2.7/index.php?page=misc/fundamentals I will probably create a PR for SHNG

**Comment by psilo909** [comment]
just did a rollback from the PR. Charts working fine now. 

Will try 1i now.

**Comment by psilo909** [comment]
1i not changing anything:
![gg](https://cloud.githubusercontent.com/assets/15831643/17836192/7c817f9a-6789-11e6-9d72-25ae0865eeaa.PNG)

**Comment by psilo909** [comment]
but i have to admit i am testing vs shng DEV. but there shouldnt be any changes which affect the behavior

**Comment by i-am-offline** [comment]
I'll try SHNG Dev too ...

**Comment by psilo909** [comment]
sample answer: 1471766421734,50.66,1471768115850,50.66,1471767068594,50,1471768115850,50

**Comment by psilo909** [comment]
order of timestamps seems to be right

**Comment by psilo909** [comment]
ich habe das jetzt eindeutig bis zum sqlite_visu28 plugin weiterverfolgt:
![fdf](https://cloud.githubusercontent.com/assets/15831643/17836887/5bee0adc-67a2-11e6-9a47-e6ccb9205ca8.PNG)

**Comment by psilo909** [comment]
Query dazu: SELECT MIN(_start), ROUND(SUM(_avg * _dur) / SUM(_dur), 2) from num WHERE _item='corridor_gf.temperature.humidity' AND _start + _dur >= 1471735208318 AND _start <= 1471778348318 GROUP by CAST((_start / 431400) AS INTEGER) ORDER BY _start ASC

**Comment by psilo909** [comment]
auf den letzten Werten kriege ich 100% einen Dreher. Da die DB sauber initialisiert war, wird das schon bei allen so sein m.E. 
Ich denke SHNG hat mit den 0h Probleme.

**Comment by psilo909** [comment]
wobei, ich sehe, die timestamps passen hier..

**Comment by psilo909** [comment]
Kommt im plot.period an:

1471766421702,24.12
1471767668561,24
1471768268494,23.9
1471768868427,23.8
1471770068312,23.5
1471770668251,23.3
1471771268175,23.1
1471774267826,22.9
1471774867759,22.8
1471776067624,23
1471776667575,23.2
1471779059699,23.2
1471778467358,23.3
1471779059699,23.3

SQL Ausgabe:

"1471766421702"	"24.12"
"1471767668561"	"24.0"
"1471768268494"	"23.9"
"1471768868427"	"23.8"
"1471770068312"	"23.5"
"1471770668251"	"23.3"
"1471771268175"	"23.1"
"1471774267826"	"22.9"
"1471774867759"	"22.8"
"1471776067624"	"23.0"
"1471776667575"	"23.2"

SELECT MIN(_start), ROUND(SUM(_avg * _dur) / SUM(_dur), 2) from num WHERE _item='corridor_gf.temperature.state' AND _start + _dur >= 1471735859699 AND _start <= 1471779059699 GROUP by CAST((_start / 432000) AS INTEGER) ORDER BY _start ASC

**Comment by psilo909** [comment]
ich befürchte fast, dass wir die Verarbeitung von NOW in SHNG nicht unterschätzen dürfen

**Comment by i-am-offline** [comment]
Ich habe mal die timestamp-generierung gedebugt. Die läuft für 0h so wie sie soll.

Bei denen Werten ist auffällig, dass der letzte Wert nochmal mehrfach hinzugefügt wird. Ich habe mir daraufhin nochmal das sqlite_visu2_8 plugin genauer anschaut und in der Tat gibt es bin "_series" einen else-Zweig "if end != 'now'" also eine Sonderroutine für das "now"

**Comment by psilo909** [comment]
das dachte ich auch erst, aber er kann aus den tuples nicht mehr holen als das sql hergibt

**Comment by psilo909** [comment]
drum muss es m.E. DANACH appended werden..

**Comment by psilo909** [comment]
und in meinem beispiel oben siehst du gut, dass im SQL nicht mehr drinsteckt als das was eigentlich soll

**Comment by psilo909** [comment]
ich kommentiere mal meinen verdaechtigen aus.

**Comment by psilo909** [comment]
das zickzack ist weg, aber offenbar geht anderes zeug jetzt nichtmehr 
![gfg](https://cloud.githubusercontent.com/assets/15831643/17836951/9976cbfc-67a5-11e6-9356-61f0ac90d2ac.PNG)

**Comment by psilo909** [comment]
if item_change < iend:
            value = float(_item())
            if item_change < istart:
                pass #tuples.append((istart, value))
            elif init:
                pass #tuples.append((item_change, value))
            if init:
                tuples.append((iend, value))

**Comment by i-am-offline** [comment]
Ich hätte vermutet dass die URsache ein paar Zeilen höher liegt:

            if end != 'now':
                tuples.append((iend, tuples[-1][1]))

**Comment by psilo909** [comment]
grundlegend sollten wir aber nicht an der stelle jetzt rumbauen. wir haben die 1.2 gerade erst released und wenn wir hier im core nen fix bauen, geht bei alten usern garnichts mehr mit der SV

**Comment by psilo909** [comment]
nein, weil in den tuples nur die DB Results sind. und da sind die Zeilen nicht drin

**Comment by psilo909** [comment]
wow.. habs auskommentiert.. jetzt gehen sie. du hast doch recht.. was macht -1 hier?

**Comment by psilo909** [comment]
if tuples:
            if istart > tuples[0][0]:
                tuples[0] = (istart, tuples[0][1])
            if end != 'now':
                pass #tuples.append((iend, tuples[-1][1]))

**Comment by i-am-offline** [comment]
-1 sollte das letzte Element in den tuples sein

**Comment by psilo909** [comment]
bei uns kommt jetzt leider besuch, aber an der stelle müssen wir wohl oder übel ansetzen, oder nen anderen fix in der sv bauen.. ohne es 100% zu verstehen sollten wir aber noch nichts beschliessen. warum kam das bei dir eigentlich nicht?

**Comment by i-am-offline** [comment]
Ich denke es ist eine Schwachstelle des sqlite-Plugins, dass an mehreren Stellen explizit auf "now" geprüft wird. "0h" hat die gleiche Bedeutung, wird aber nicht korrekt verarbeitet. Warum es bei mir keine Probleme gab, kann ich dir leider noch nicht sagen. Werde ich aber mal untersuchen.
Trotzdem hast du natürlich recht, eine Inkonsistenz zwischen SHNG und SV ist beiden Projekten nicht förderlich. 
Ich denke, dass ich diesen Fix so umbauen kann, dass statt "0h" doch "now" als Default-Wert verwendet wird und "0" bzw. "0h" zu "now" ersetzt werden. Dann sollte SHNG die korrekten Werte liefern.
In einem zweiten Schritt wäre dann dafür zu sorgen, dass SHNG auch für "0h" die korrekten Werte liefert.
Wenn das beides released ist kann man überlegen, ob man in SV wieder "0h" als Default-Wert verwendet.

**Comment by psilo909** [comment]
wenn das database plugin für die shng 1.3 mal was wird, könnte man auch da gleich alles anpassen und das alte sqlite verbannen

**Comment by psilo909** [comment]
bisher crasht - vermutlich wegen multithreading problemen - mein shng mit dem database plugin nur alle paar tage.

**Comment by i-am-offline** [comment]
Ich konnte das Problem nun bei mir nachvollziehen. Ich habe dabei gelernt, dass 

    define('config_cache', 'off');

den SV-Cache nicht wirklich deaktiviert :angry: 
Gleichzeitig scheint das Problem nicht offensichtlich zu sein, wenn viele Datenpunkte im Plot sind.

Mit dem PR #18 wird die oben beschriebene Änderung hinsichtlich SV vorgenommen

**Comment by psilo909** [comment]
looks good at the moment -> close

**Comment by smaiLee** [comment]
Ist dieser Issue mit dem PR #18 endgültig gefixt oder ist noch was offen?

**Comment by psilo909** [comment]
@smaiLee erstmal ist er gefixt, wir sollten uns aber überlegen, ob wir synchron shng 1.3 und die sv so umbauen, dass wir anstatt now das 0h annehmen.

**Comment by i-am-offline** [comment]
Ich glaube, ich habe eine Lösung das 0h-Problem im sqlite-Plugin von SHNG gefunden. Ich teste aber noch. Da eine Lösung aber erst in eine zukünftige Version von SNNG einfließen wird, sollte vorerst "now" der default-Wert bleiben.

**Comment by psilo909** [comment]
seit dem einspielen des PRs habe ich jetzt das problem, dass bei jedem seitenwechsel erst nach f5 die daten wieder da sind. kann das jemand reproduzieren?
