### ISSUE TITLE
Have some kind of page checker

### ISSUE THREAD

**Issue by i-am-offline** [SmartVisuTNG/smartvisu#20]
It would be good to to have some kind of page checker that checks a set of pages for probable issues. 
The main issue which needs checking at the moment is, that the .png icons have been replaced by .svg icons in v 2.8.

The page checker should have three main functions

- Check pages for issues and show them.
- Propose solution (possibly editable).
- Apply solution to file if user wants to.

**Comment by smaiLee** [comment]
This issue was moved to Martin-Gleiss/smartvisu#64
