### ISSUE TITLE
Drop support for iconseries in basic.shifter

### ISSUE THREAD

**Issue by i-am-offline** [SmartVisuTNG/smartvisu#21]
basic.shifter works perfectly with svg-images. 
Iconseries are a hangover from the .png era. I've made basic.shifter with iconseries work basically while working on #14, but I consider this as outdated.

It should be discussed if iconseries support in basic.shifter can be dropped. However, there are some nice iconseries (e.g. fts_garage*) which should be converted in a dynamic svg-image first.

**Comment by smaiLee** [comment]
This issue was moved to Martin-Gleiss/smartvisu#65
