### ISSUE TITLE
Configuration Page: Changes not visible after save

### ISSUE THREAD

**Issue by smaiLee** [SmartVisuTNG/smartvisu#22]
After pressing "save" on configuration page, the old values are displayed again.
But the changes are saved and after refresh they are also shown on configuration page.

**Comment by psilo909** [comment]
den gibts aber schon seit ich die SV kenne ;-) oder ist das nur zum tracken des issues?

**Comment by smaiLee** [comment]
Deshalb hat er ja auch das Label "older than 2.8". Gefixt werden sollte er ja trotzdem irgendwann.

**Comment by psilo909** [comment]
gutgutgut ich bin blind :)

**Comment by smaiLee** [comment]
This issue was moved to Martin-Gleiss/smartvisu#66
