### ISSUE TITLE
Fix small issues with widgets

### ISSUE THREAD

**Issue by i-am-offline** [SmartVisuTNG/smartvisu#23]
I found some (small) issues in some widgets. I will assign the commits to this issue.

**Comment by smaiLee** [comment]
I think some issues have been introduced by [commit ae5f5453cbf5657900e887bbe4f273e0ca08c0de](https://github.com/SmartVisuTNG/smartvisu/commit/ae5f5453cbf5657900e887bbe4f273e0ca08c0de)
@aschwith has implemented my performance patch, but there were lots of other changes in his widget.js

**Comment by i-am-offline** [comment]
Small issues have been fixed, closing this issue.
