### ISSUE TITLE
Layout problem in config page

### ISSUE THREAD

**Issue by psilo909** [SmartVisuTNG/smartvisu#27]
After introducing the Auto Relad in the config, we need a br style="clear:both;" after the I/O Connection block, as divs start floating around pretty ugly.

**Comment by smaiLee** [comment]
IMHO this option should be in _I/O Connection_ and not in _Interface_ anyway.
And i don't like the script as inline in root.html.
I will refactor this on occasion.

**Comment by smaiLee** [comment]
Done by [commit 501a4d8f7e3acd8da328209c8be10bb720a32564](https://github.com/SmartVisuTNG/smartvisu/commit/501a4d8f7e3acd8da328209c8be10bb720a32564)
