### ISSUE TITLE
now vs 0 and replacement line in io_smarthome.js

### ISSUE THREAD

**Issue by psilo909** [SmartVisuTNG/smartvisu#9]
I have an issue with plots. A the moment, if i set a "now" as tmax i get the following behavior:
- the data-item is initialized with a "now"
- the now is sent to shng
- a now is returned
- the "now" is replaced by a 0 in io_smarthome... (Line 141)
- the data item is not found, as it contains a now and not a 0

In case the replacement line is removed:
- for the "now" case all is working fine
- in case i set 0 the SV sends a NOW to smarthomeNG (REASON Line 224: io.send({'cmd': 'series', 'item': item, 'series': pt[pt.length - 4], 'start': pt[pt.length - 3], 'end': (pt[pt.length - 2] == '0' ? 'nfow' : pt[pt.length - 2]), 'count': pt[pt.length - 1]});
- despite the default, the data-item has 0 (data-item="utility_room.temperature.state.avg.12h.0.100")
- a now is returned and not replaced
- the data-item has 0 (data-item="utility_room.temperature.state.avg.12h.0.100") and cannot be found

we should decide for a solution and an alternative, e.g. not to allow "now" anymore or to fix the "default now" in the 2nd case.

so far, none of both alterantives really work.

**Comment by psilo909** [comment]
currently, due to the behavior above, the rtr in plot.html makes problems, as there is a "now" set:
<div id="{{ uid(page, id) }}" data-widget="plot.rtr" data-item="{{ implode([item_actual, item_set, item_state], ['avg', '1d', 'now', count|default(100)]) }}"

**Comment by i-am-offline** [comment]
I would propose the following:

- The interface should not make any replacements, neither when sending, nor when receiving data.
- The default value for tmax should be changed to "0h" (which is actually "now")
- For compatibility reasons, plots should accept the value "now" for tmax, but change it into "0h" BEFORE using it for anything (e.g. naming objects etc.)

PR will follow so anyone can test

**Comment by psilo909** [comment]
not sure if "0h" is evaluated correctly by smarthome.py. please test the combination before the PR

**Comment by i-am-offline** [comment]
I already did. "0h" is working. What is not working is "0", but as this is not a [Duration Format] (http://docu.smartvisu.de/2.7/index.php?page=misc/fundamentals) this should not affect this issue.

**Comment by psilo909** [comment]
huh, currently 0 is working for me?!

**Comment by i-am-offline** [comment]
Currently the interface replaces "0" with "now" which is supported by SHNG. After removing this "0" would be send to SHNG. This causes SNHG to log

    WebSocket: no entries for series <item> avg

instead of returning data.
But you are right, as it is working now, it should remain working. I just saw that even the docu uses value 0 for tmax.
For now we could just handle it like "now" and replace it by "0h".


"0" can be handled similar to "now".

**Comment by psilo909** [comment]
ok you are right, 0 is replaced by now and now is then (backward) replaced by 0...

**Comment by psilo909** [comment]
PS: i like the solution!

**Comment by i-am-offline** [comment]
OK that's it. I've tested this on my own installation against SmartHomeNG release-1.2 branch
As I'm not using all types of plots it might not be bad if someone else could test, too.

**Comment by smaiLee** [comment]
Fixed by #10
